// AboutWindow.h
// Generated by Interface Elements (Window v2.2) on Jan 7 1999
// This is a user written class and will not be overwritten.

#ifndef _ABOUTWINDOW_H_
#define _ABOUTWINDOW_H_

#include "IEWindow.h"
#include "AboutWindowDefs.h"


class AboutWindow : public IEWindow
{
public:
	AboutWindow(void);
	~AboutWindow(void);

};

#endif
