// AboutWindowDefs.h
// Generated by Interface Elements (Window v2.3) on May 14 1999
// Do not modify this file!



/*

Views in AboutWindow:
	"AboutBackground"  (BView)
	"AboutVersion"  (BStringView)
	<unnamed> (BStringView)
	<unnamed> (BStringView)
	<unnamed> (BStringView)
	<unnamed> (BStringView)
	<unnamed> (BStringView)
	<unnamed> (BStringView)

*/


