// SettingsWindowDefs.h
// Generated by Interface Elements (Window v2.3) on May 14 1999
// Do not modify this file!



/*

Views in SettingsWindow:
	"SettingsBack"  (BView)
	"SettingsSaveWindow"  (BCheckBox)
	"SettingsSaveWorkspace"  (BCheckBox)
	"SettingsRefresh"  (BTextControl)
	"_input_"  (_BTextInput_)
	"SettingsRevert"  (BButton)
	<unnamed> (BBox)
	"SettingsCurrentWorkspace"  (BRadioButton)
	"SettingsSavedWorkspace"  (BRadioButton)
	"SettingsAllWorkspaces"  (BRadioButton)
	"SettingsDeskbar"  (BButton)

*/


// Message constants:
enum {
	IE_SETTINGSWINDOW_SETTINGSSAVEWORKSPACE = 0x5L,
	IE_SETTINGSWINDOW_SETTINGSREFRESH = 0xAL,
	IE_SETTINGSWINDOW_SETTINGSREVERT = 0x63L,
	IE_SETTINGSWINDOW_SETTINGSCURRENTWORKSPACE = 0x5AL,
	IE_SETTINGSWINDOW_SETTINGSSAVEDWORKSPACE = 0x5EL,
	IE_SETTINGSWINDOW_SETTINGSALLWORKSPACES = 0x5CL,
	IE_SETTINGSWINDOW_SETTINGSDESKBAR = 0x68L
};

